export const queryKeys = {
  user: 'user',
  notes: 'notes',
  tags: 'tags',
  tagsByCategory: 'tagsByCategory',
  employees: 'employees',
  employee: 'employee',
  teams: 'teams',
  roles: 'roles',
  actions: 'actions',
  deletedActions: 'actions-deleted',
  permissions: 'permissions',
  colors: 'colors',
  categories: 'categories',
};
